# Generated by Django 4.2.13 on 2024-06-24 07:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ecommerce', '0002_alter_product_type_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('Smartphones', 'Smartphones'), ('Smartwatches', 'Smartwatches'), ('Games', 'Video Games'), ('Computers', 'Computers & Accessories'), ('Headphones', 'Headphones'), ('Camera', 'Camera & Photo'), ('TV', 'TV'), ('Speakers', 'Speakers')], max_length=30),
        ),
    ]
