# Generated by Django 4.2.13 on 2024-06-24 09:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ecommerce', '0004_cartitem_alter_product_type_delete_cart_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('Games', 'Video Games'), ('TV', 'TV'), ('Camera', 'Camera & Photo'), ('Speakers', 'Speakers'), ('Computers', 'Computers & Accessories'), ('Smartphones', 'Smartphones'), ('Headphones', 'Headphones'), ('Smartwatches', 'Smartwatches')], max_length=30),
        ),
    ]
