# Generated by Django 4.2.13 on 2024-06-24 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0005_alter_cartitem_user_alter_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('Smartwatches', 'Smartwatches'), ('Speakers', 'Speakers'), ('Camera', 'Camera & Photo'), ('Headphones', 'Headphones'), ('Smartphones', 'Smartphones'), ('Games', 'Video Games'), ('TV', 'TV'), ('Computers', 'Computers & Accessories')], max_length=30),
        ),
    ]
